# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucmuolSCwFtP03yqS4s049ZatUucu8JL
"""

import streamlit as st

st.title("안녕하세요, 스트림릿!")
st.write("이것은 Streamlit에서 실행되는 아주 간단한 웹앱입니다.")